export const BASE_OPTIONS = {
  type: 'mysql',
  host: 'localhost',
  port: 3306,
  username: 'root',
  password: '',
  database: 'blog',
  entities: ['dist/**/*.entity{.ts,.js}'],
  dropSchema: false,
  synchronize: true,
  migrationsRun: false,
  logging: true,
  migrations: ['dist/src/db/*{.ts,.js}'],
  migrationsTableName: 'migrations',
};
